apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::322261369682:role/eksctl-robin-personal-cluster-nod-NodeInstanceRole-1VZDP5964EGHS
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::322261369682:role/eksctl-robin-personal-cluster-nod-NodeInstanceRole-HCKW1G8J2WD9
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-12-07T11:43:15Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2479"
  uid: 076f47c2-7e98-44e7-b6fb-1e64d005930c
