apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::322261369682:role/eksctl-robin-personal-cluster-nod-NodeInstanceRole-1VZDP5964EGHS
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::322261369682:role/eksctl-robin-personal-cluster-nod-NodeInstanceRole-HCKW1G8J2WD9
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::322261369682:user/ekstrainee
      username: ekstrainee
    - userarn: arn:aws:iam::322261369682:user/eksadmin
      username: eksadmin
    - userarn: arn:aws:iam::322261369682:user/eksdeveloper
      username: eksdeveloper
    - userarn: arn:aws:iam::322261369682:user/superadmin
      groups:
      - system:masters
      username: superadmin
